### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by danielaik** [jayunruh/Jay_Plugins#2]
Hi, I am trying to compile the Plugin but encounter several issue. Mostly are dependencies. May I have the list of dependencies or the pom.xml 

Other issue:
-PU.unmix_phasor_geom3

List of library:
<img width="270" alt="Screenshot 2021-10-26 at 11 02 56 AM" src="https://user-images.githubusercontent.com/48349272/138802289-2ea64f4e-0650-4547-a633-a26da65aebbe.png">

**Comment by jayunruh** [comment]
Here are all of the jar files I used for compilation: 
quickhull3d
biojava-core-5.1.1
biojava-alignment-5.1.1
Jama-1.0.2
bioformats_package
ImarisLib
imglib2-ij-2.0.0-beta-44
imglib2-5.6.3
mpicbg-1.1.1
JOCL-0.1.9
opencv-300
AnalyzeSkeleton_-2.0.5
jmatio

The PU.java file contains proprietary code that I can't share under the GPL license model.
